//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.BusesToLines = new HashSet<BusesToLine>();
        }
    
        public int Id { get; set; }
        public string BusId { get; set; }
        public string PlateNumber { get; set; }
        public int BusType { get; set; }
        public int Occupation { get; set; }
        public int Owner { get; set; }
        public int GpsSource { get; set; }
        public string GpsCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusesToLine> BusesToLines { get; set; }
    }
}
