
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class BusesToLine
{

    public int Id { get; set; }

    public int LineId { get; set; }

    public int BusId { get; set; }



    public virtual Bus Bus { get; set; }

    public virtual Line Line { get; set; }

}

}
