//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Line()
        {
            this.BusesToLines = new HashSet<BusesToLine>();
            this.Schedules = new HashSet<Schedule>();
            this.StationsToLines = new HashSet<StationsToLine>();
        }
    
        public int Id { get; set; }
        public string LineName { get; set; }
        public string LineNumber { get; set; }
        public string HexColor { get; set; }
        public int Direction { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> totalStudents { get; set; }
        public string PathGeometry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusesToLine> BusesToLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationsToLine> StationsToLines { get; set; }
    }
}
