
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class Login
{

    public int userId { get; set; }

    public string userName { get; set; }

    public string Password { get; set; }

    public bool emailConfirm { get; set; }

    public string passwordUnSecure { get; set; }

    public Nullable<int> familyId { get; set; }

}

}
