//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business_Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Direction { get; set; }
        public int LineId { get; set; }
        public int DriverId { get; set; }
        public int BusId { get; set; }
        public System.DateTime FirstStationStartTime { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Line Line { get; set; }
    }
}
