
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblAlertsQueue
{

    public int id { get; set; }

    public Nullable<System.DateTime> datetime { get; set; }

    public string action { get; set; }

    public string controler { get; set; }

    public Nullable<bool> active { get; set; }

    public Nullable<int> messageType { get; set; }

    public Nullable<bool> sendSMS { get; set; }

    public Nullable<bool> sendEmail { get; set; }

    public string messageA { get; set; }

    public string messageB { get; set; }

    public string messageC { get; set; }

    public string title { get; set; }

    public Nullable<int> EmailList { get; set; }

    public Nullable<int> smsList { get; set; }

    public Nullable<System.DateTime> startTime { get; set; }

    public Nullable<int> totalTimes { get; set; }

    public Nullable<int> durationSec { get; set; }

    public Nullable<int> totalSend { get; set; }

}

}
