
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblCalendar
{

    public int pk { get; set; }

    public Nullable<System.DateTime> date { get; set; }

    public string month { get; set; }

    public string HebMonth { get; set; }

    public string day { get; set; }

    public Nullable<bool> active { get; set; }

    public string @event { get; set; }

    public string HebDate { get; set; }

}

}
