
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblDictSystem
{

    public int id { get; set; }

    public string term { get; set; }

    public string CustomerTranslated { get; set; }

    public string SystemTranslated { get; set; }

    public string cultures { get; set; }

    public string status { get; set; }

    public Nullable<System.DateTime> DateCreatedUTC { get; set; }

    public Nullable<bool> cantBeChange { get; set; }

}

}
