
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Business_Logic
{

using System;
    using System.Collections.Generic;
    
public partial class tblSetting
{

    public int Id { get; set; }

    public Nullable<bool> PopulateLinesIsActive { get; set; }

    public Nullable<System.DateTime> PopulateLinesLastRun { get; set; }

}

}
